### ISSUE TITLE
Search/filter messages by more content

### ISSUE THREAD

**Issue by adamal** [DigitalMolecules/vscode-servicebus-explorer#50]
It appears "Search Messages" only searches for exact matches on message id.
[Source seems to confirm.](https://github.com/DigitalMolecules/vscode-servicebus-explorer/blob/e938640cc30cae9d0bde5dad2e70d55db844b635/src/client/ServiceBusClient.ts#L127)

It would be very useful to
1) Have the behaviour documented (perhaps simply changing the "Search Messages" to "Find message by id"

2) Be able to do more advanced filtering on Label and content.

**Comment by andreujuanc** [comment]
Sounds fair, Would you like to give it a go ? C:

**Comment by adamal** [comment]
Hmm. I might. But I'm not sure where to start with a dev env for local testing.

**Comment by nspiteri** [comment]
> Hmm. I might. But I'm not sure where to start with a dev env for local testing.

There is a devcontainer if you have wsl2 and docker.  
Otherwise you can fork the repo and open it in vscode.

If you run the folder (in vscode), it will open another vscode instance.  You can then put breakpoints in the first instance and debug accordingly.

**Comment by nspiteri** [comment]
I developed a fix for this..assuming its a raw json.  Maybe in the future we can improve it a bit.
