### ISSUE TITLE
Add ability to purge Dead Letter Queue

### ISSUE THREAD

**Issue by adamal** [DigitalMolecules/vscode-servicebus-explorer#61]
I frequently have a need to do this, but can't from my mac as of now.

With [the hints here](https://github.com/DigitalMolecules/vscode-servicebus-explorer/issues/50#issuecomment-638001994), I have added two actions that does this for Queues and Subscriptions respectively.

Would you consider a pull request?

**Comment by andreujuanc** [comment]
Of course! I'm checking your PR right now.

**Comment by andreujuanc** [comment]
Closing  https://github.com/DigitalMolecules/vscode-servicebus-explorer/pull/63
